### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by RahullRawat**

### CODE REVIEW

**Comment by Husain01** [comment]
Looks pretty clean and great. Nice color you've chosen

**Comment by RahullRawat** [comment]
> Looks pretty clean and great. Nice color you've chosen

Thankyou Husain

**Review by VishalPatil18 — APPROVED** [review]
The code and the UI look pretty clean! Well Done Rahul 👍 
The name is 🔥

**Comment by RahullRawat** [comment]
> The code and the UI look pretty clean! Well Done Rahul 👍 The name is 🔥

Thanks Vishal 😊

**Comment by RakshaPawar108** [comment]
The code looks clean and the UI is also very minimalistic and pretty on desktop. You can try making the page responsive using a few media queries as some of the content is overflowing on the header on smaller screen sizes.

**Comment by RahullRawat** [comment]
> The code looks clean and the UI is also very minimalistic and pretty on desktop. You can try making the page responsive using a few media queries as some of the content is overflowing on the header on smaller screen sizes.

sure raksha, i will do that

**Pull request merged**
